import Heading from "./components/Heading";
import InputField from "./components/InputField";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="m-6 font-serif md:max-w-4xl md:flex md:flex-col md:justify-center md:mx-auto">
          <Heading />
          <InputField />
          {children}
        </div>
      </body>
    </html>
  );
}
